version: '3'
services:
  db:
    image: postgres:15
    container_name: postgres_container
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin
      POSTGRES_DB: btl_ktpm
    ports:
      - "32442:5432"
    volumes:
      - pg_data:/var/lib/postgresql/data

volumes:
  pg_data: